### ISSUE TITLE
Hi. 👋

### ISSUE THREAD

**Issue by diamantdev** [DonovanDMC/OwOWhatsThis#1]
It's not really a way out, it was just to find a way to write you.

I admit I'm not a user of this mod (as I don't play minecraft) but I love the concept and idea of the mod. I guess this mod has been deleted from CurseForge, that's why I just wanted to write some little words of support and encouragement, it's a beautiful and nice mod and I hope you'll manage to find a way to publish it other than here and that it won't be deleted.

~~Long live to the femboy.~~

**Comment by DonovanDMC** [comment]
The other mod with the nsfw content was removed from curseforge for being adult content, it has now been split into [OwO What's This?!?](https://github.com/DonovanDMC/OwOWhatsThis) and [OwO What's This?!?: NSFW Addon](https://github.com/DonovanDMC/FemboyStuff)

The new curseforge link is [here](https://www.curseforge.com/minecraft/mc-mods/owo-whats-this)
